<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <ShiroBotPluginPackagingEnabled>true</ShiroBotPluginPackagingEnabled>
    <ShiroBotPluginSharedAssemblies>ShiroBot.Model.QQ</ShiroBotPluginSharedAssemblies>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ShiroBot.SDK\ShiroBot.SDK.csproj" />
    <ProjectReference Include="..\ShiroBot.Model.QQ\ShiroBot.Model.QQ.csproj" />
  </ItemGroup>

  <Import Project="..\ShiroBot.SDK\buildTransitive\ShiroBot.SDK.props" />
  <Import Project="..\ShiroBot.SDK\buildTransitive\ShiroBot.SDK.targets" />
</Project>
