name: shirobot

services:
  shirobot:
    image: ghcr.io/shirokaproject/shirobot:${SHIROBOT_IMAGE_TAG:-latest}
    pull_policy: always
    restart: unless-stopped
    ports:
      - "127.0.0.1:7001:7001"
    volumes:
      - shirobot-data:/data

volumes:
  shirobot-data:
