<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Avalonia" Version="12.1.2" />
    <PackageVersion Include="Avalonia.HarfBuzz" Version="12.1.1" />
    <PackageVersion Include="Avalonia.Headless" Version="12.1.2" />
    <PackageVersion Include="Avalonia.Markup.Xaml.Loader" Version="12.1.2" />
    <PackageVersion Include="Avalonia.Skia" Version="12.1.2" />
    <PackageVersion Include="Avalonia.Themes.Fluent" Version="12.1.1" />
    <PackageVersion Include="ILRepack.Lib.MSBuild.Task" Version="2.0.46" />
    <PackageVersion Include="Spectre.Console" Version="0.57.2" />
    <PackageVersion Include="System.CommandLine" Version="3.0.0-preview.6.26359.118" />
    <PackageVersion Include="Tomlyn" Version="2.10.1" />
  </ItemGroup>
</Project>