<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <ShiroBotPluginPackagingEnabled>true</ShiroBotPluginPackagingEnabled>
    <!--#if (useQq)-->
    <ShiroBotPluginSharedAssemblies>ShiroBot.Model.QQ</ShiroBotPluginSharedAssemblies>
    <!--#endif-->
    <!--#if (useDiscord)-->
    <ShiroBotPluginSharedAssemblies>ShiroBot.Model.Discord</ShiroBotPluginSharedAssemblies>
    <!--#endif-->
    <!--#if (useTelegram)-->
    <ShiroBotPluginSharedAssemblies>ShiroBot.Model.Telegram</ShiroBotPluginSharedAssemblies>
    <!--#endif-->
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ShiroBot.SDK" />
  </ItemGroup>

</Project>
