<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <IsPackable>false</IsPackable>
        <Version>$(ShiroBotProductVersion)</Version>
        <AssemblyVersion>$(ShiroBotSdkAbiVersion)</AssemblyVersion>
        <FileVersion>$(ShiroBotFileVersion)</FileVersion>
        <EnablePackageValidation>true</EnablePackageValidation>
        <NoWarn>$(NoWarn);NU5104</NoWarn>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Avalonia" />
      <PackageReference Include="Avalonia.HarfBuzz" />
      <PackageReference Include="Avalonia.Skia" />
      <PackageReference Include="ILRepack.Lib.MSBuild.Task"
                        PrivateAssets="all"
                        GeneratePathProperty="true" />
    </ItemGroup>

    <ItemGroup>
      <FrameworkReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>

    <ItemGroup>
    </ItemGroup>

</Project>
